archway-network/archway

- x/gastracker/abci.go
Method BigInt currently returning a value of: 6491055731293290496, because it uses 18 decimal, but the correct value should be: 402496, which is corrected by RoundInt.
> Update GasConsumed decimals value

- ci/titus-1.yaml
Storage resize policy changed from "auto" to "fixed" due to `starport.cloud` issue with PVC resize.
> Titus-1 testnet fix

- x/gastracker/ante/ante.go
- x/gastracker/ante/ante_test.go
- x/gastracker/keeper/grpc_query.go
- x/gastracker/keeper/keeper.go
- x/gastracker/keeper/keeper_contract_gas_processor.go
- x/gastracker/keeper/keeper_test.go
- x/gastracker/keys.go
- x/gastracker/module/abci.go
- x/gastracker/module/abci_test.go
- x/gastracker/testutil/testutil.go
Initially TX tracking plus contracts operations were all saved into a single object.
This brings huge performance limitations and issues.
As to add 1 contract operation, you need to unmarshal one single object containing all the txs (and their respective operations) and then append to it, and then marshal it back again.
In blocks with lots of TXs this gets crazy expensive.
So this PR puts every tx tracking information into its own object.
This could be better improved by putting every single operation into its own object and doing all the connections when the block tracking info is fetched. Leaving this for another PR to reduce the scope.
On top of that it also removes copied test utilities.
> change: improve TX tracking

- docker-compose.yaml
Previously running `make localnet` resulted in:
```
❯ docker version
Client:
Version:           20.10.17
❯ docker-compose version
Docker Compose version 2.6.1
❯ make localnet
docker-compose up
[+] Running 1/1
⠿ Container archway-node-1  Recreated                                      0.2s
Attaching to archway-node-1
archway-node-1  | Error: unknown command "sh" for "archwayd"
archway-node-1  |
archway-node-1  | Did you mean this?
archway-node-1  | 	tx
archway-node-1  |
archway-node-1  | Run 'archwayd --help' for usage.
archway-node-1 exited with code 1
```
This PR overrides the archwayd container entrypoint to be the `/opt/localnet.sh` script
> fix: make localnet - override entrypoint in docker-compose.yaml

- x/rewards/keeper/metadata_test.go
- x/rewards/keeper/msg_server_test.go
Closes: #234
Added tests for 
- `SetContractMetadata`
- `WithdrawRewards`
> tests: Adding msg server tests for x/rewards

- x/rewards/keeper/grpc_query_test.go
Closes: #235
Added tests for 
- `Params`
- `ContractMetadata`
- `BlockRewardsTracking`
- `RewardsPool`
- `EstimateTxFees`
- `OutstandingRewards`
- `RewardsRecords`
> tests: Adding query server tests for x/rewards

- Makefile
When someone builds from the `main` branch, the version shown in the `archwayd version` command does not give enough information if the binary was created from a tag or a standalone commit. This change in the Makefile fixes this issue.
> fix(version): add the commit info to the current version

- .github/workflows/go-lint.yaml
- .golangci.yml
- e2e/testing/chain_ops.go
- e2e/testing/ibc_path.go
Closes: #239
- Added linter checking gh action 
- Fixed existing linting issues in the repo where error return value was not checked
> ci: adding golang linter

- .github/workflows/changelog.yaml
- CHANGELOG.md
Closes: #240
- Added gh action to ensure CHANGELOG is updated when PR targets to main
- Updating changelog format to [keepachangelog](https://keepachangelog.com/)
> ci: adding changelog check to PRs targeting main

- .github/workflows/pr-lint.yaml
Closes: #238
- Added gh action with [`amannn/action-semantic-pull-request@v5`](https://github.com/amannn/action-semantic-pull-request) that ensures that the PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/)
> ci: adding lint-pr gh action 

- CHANGELOG.md
- wasmbinding/msg_plugin.go
- wasmbinding/pkg/wasm_coins.go
- wasmbinding/query_plugin.go
- wasmbinding/rewards/common_test.go
- wasmbinding/rewards/msg_handler.go
- wasmbinding/rewards/query_handler.go
- wasmbinding/rewards/types/msg_flatfee.go
- wasmbinding/rewards/types/msg_test.go
- wasmbinding/rewards/types/query_flatfee.go
- wasmbinding/rewards/types/query_test.go
- wasmbinding/types/msg.go
- wasmbinding/types/query.go
- x/rewards/ante/min_cons_fee_test.go
- x/rewards/keeper/flat_fee.go
- x/rewards/keeper/flat_fee_test.go
- x/rewards/keeper/grpc_query_test.go
- x/rewards/keeper/msg_server.go
- x/rewards/spec/08_wasm_bindings.md
- x/rewards/types/errors.go
Closes: #279
* Add msg plugin wasm binding for `SetFlatFee`
* Add query plugin wasm binding for `FlatFee`
* Wasmbindings tests
* Updated spec
* Updating `keeper.SetFlatFee` to perform the authorization check. (used to happen in msgSrvr before)
┆Issue is synchronized with this [Jira Task](https://phi-labs.atlassian.net/browse/ARCH-36) by [Unito](https://www.unito.io)
> feat(x/rewards): Contract premium - Wasmbindings

- x/mint/types/params.go
- x/mint/types/params_test.go
Previously, `params.Validate()` would pass when there were multiple `params.InflationRecipients` with same name. 
Example: 
```go
[]*types.InflationRecipient {
{Recipient: authtypes.FeeCollectorName, Ratio:  sdk.MustNewDecFromStr("0.4")},
{Recipient: authtypes.FeeCollectorName, Ratio:  sdk.MustNewDecFromStr("0.6")},}
```
this used to be valid before. 
Now it throws `ErrInvalidInflationRecipient` error
> fix(x/mint): params.InflationRecipients validates error on multiple recipients with same name

- .github/workflows/release.yaml
This fixes the current issues with the release workflow by adding extra step to the workflow
```
Error: fatal: detected dubious ownership in repository at '/__w/archway/archway'
```
> fix: add safe directory step to the workflow

- CHANGELOG.md
- x/rewards/keeper/grpc_query.go
- x/rewards/keeper/grpc_query_test.go
Closes: #334 
* Fixed the sdk.Coins addition such that when both minConsFee and contract flatfee are same denom it doesnt error
* Test case for this issue
> fix(x/rewards): fixed `EstimateTxFees` error when minConsFee and contract flatfee are same denom

- CHANGELOG.md
- app/ante.go
- e2e/rewards_test.go
- x/rewards/ante/ante_utils.go
- x/rewards/ante/fee_deduction.go
- x/rewards/ante/fee_deduction_test.go
- x/rewards/ante/min_cons_fee.go
- x/rewards/ante/min_cons_fee_test.go
- x/rewards/keeper/distribution.go
- x/rewards/keeper/flat_fee.go
Ref: https://github.com/archway-network/archway/issues/336
* Modified MinFeeDecorator such that when a contract is found with flatfees configured, the relevant rewards records are created
* Modified DeductFeeDecorator such that when a contract is found with flatfees configured, the relevant amount is sent from the sender's acc to the rewards collector account
* Some refactor of x/rewards antehandlers in general with moving common stuff to ante_utils
* Added TestRewardsFlatFees to e2e rewards_tests which checks that post a successful tx completion, the relevant records for contract premium are created.
> fix(x/rewards): create block rewards for flat fees

- .github/workflows/release.yaml
- .goreleaser.yaml
- Makefile
Previous solution on building the arm64 binaries failed due to CGO limitations.
This PR now fixes those issues.
Tested with:
```
make release
```
> fix: arm64 builds working with goreleaser

- ci/titus-1.yaml
min_price_of_gas was introduced in https://github.com/archway-network/archway/pull/351
> fix(ci): Add min_price_of_gas rewards param to titus genesis

- CHANGELOG.md
The changelog was inaccurate with the releases and tags. This updates the changes
> docs: bringing changelog upto date with the releases 

- CHANGELOG.md
- go.mod
- go.sum
* Updates cosmos-sdk from v0.45.15 to v0.45.16 [^1]
[^1]: [Security fix which addresses an issue in the x/feegrant module ](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.16)
> feat: update cosmos-sdk version from v0.45.15 to v0.15.16

- CHANGELOG.md
- go.mod
- go.sum
Updates the wasmvm dependency to latest 1.2.4
> feat: bump wasmvm to 1.2.4

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/06/upgrades.go
This should address the issue where --skip-upgrade-handler still results in a panic, as CosmosSDK is checking for a downgraded binary... thus the last applied upgrade will always be needed even when using --skip-upgrade-handler;
> fix: Add upgrade handler for 0.6 back

- CHANGELOG.md
- x/genmsg/genesis.go
Message logging may significantly impact network start up performance due to excessive terminal output;
> fix: Remove genesis module msg logging

- CHANGELOG.md
- x/rewards/ante/min_cons_fee.go
* Changes to not skip the Minimum Consensus Fee ante handler when simulating the transaction. Would result in incorrect gas estimates, especially when contract premiums were setup.
> fix: fixing incorrect gas estimation when running with `--dry-run` flag

- CHANGELOG.md
- x/rewards/ante/ante_utils.go
- x/rewards/ante/min_cons_fee_test.go
Closes: #417 
- Fixing the incorrect authz msg decoding in the x/rewards ante handlers.
- Using the nice helper func provided by x/authz to unwrap the msg instead of trying it explicitly
> fix: fixing authz messages decoding issue in antehandlers 

- CHANGELOG.md
- app/app.go
- app/app_upgrades.go
- app/upgrades/2_0_0/upgrades.go
- Enabling ICA Host module with the following msgs allowed
-  `banktypes.MsgSend`
- `banktypes.MsgMultiSend`
- `stakingtypes.MsgDelegate`
- `stakingtypes.MsgUndelegate`
- `stakingtypes.MsgBeginRedelegate`
- `stakingtypes.MsgCreateValidator`
- `stakingtypes.MsgEditValidator`
- `distrtypes.MsgWithdrawDelegatorReward`
- `distrtypes.MsgSetWithdrawAddress`
- `distrtypes.MsgWithdrawValidatorCommission`
- `distrtypes.MsgFundCommunityPool`
- `govtypes.MsgVote`
- `govtypes.MsgVoteWeighted`
> feat: enable ica module

- .gitignore
- CHANGELOG.md
- Makefile
- scripts/localnet.sh
This PR adds two new make commands
1. `make run`  - This will bootstrap a new localnet on the dev machine
2. `make run-continue` - This will continue running an existing localnet on the dev machine 
The localnet has the chain-id `localnet-1` and has been configured with three accounts on startup. The localnet setup also customizes the governance parameters to be shorter duration for easier testing.
> chore: Easily run localnet

- CHANGELOG.md
- docs/adr/ADR-004-contract-premiums.md
Elaborate on Contract Premium architecture, limits and examples
> docs: Update ADR-004 Contract Premiums

- .github/workflows/go-lint.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- go.mod
- Updating go version in go.mod to 1.20
- Updating Github workflows to use go version from go mod file instead of hardcoded version
> chore: update go version to 1.20

- CHANGELOG.md
- Dockerfile.deprecated
- app/app.go
- app/app_upgrades.go
- app/upgrades/4_0_0/upgrades.go
- go.mod
- go.sum
- Bumping the wasmd fork to `v0.33.0-archway` https://github.com/archway-network/archway-wasmd/pull/6
- Adding [Cosmwasm_1_3](https://github.com/CosmWasm/cosmwasm/blob/f3d57ce2a92c55495267c426e3c9c0364bf98596/docs/CAPABILITIES-BUILT-IN.md) capabilities 
- Updated Dockerfile with updating wasmvm version. [checksum src](https://github.com/CosmWasm/wasmvm/releases)
> feat: bumping archway wasmd to v0.33.0

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/latest/upgrades.go
- interchaintest/setup.go
Now that we have a chain upgrade test https://github.com/archway-network/archway/pull/430, this forces our repository to always have an active upgrade handler. With this PR, I propose that we have a `latest` upgrade handler where all the upcoming upgrade logic goes into. This way any missing upgrade handling will be caught immediately by the developer who was working on the feature, as opposed to whoever adds in the upgrade handler prior to release. Whenever we decide to cut a release, we can rename the upgrade handler from `latest` to `v5.0.0` or something like that.
One overhead with this to keep track of is that once we tag a release, we would have to do a maintenance PR like this which creates a new upgrade handler post release.
> chore: Post release maintenance

- CHANGELOG.md
- app/app_upgrades.go
- app/app_upgrades_test.go
- app/app_upgrades_util_test.go
- app/upgrades/06/upgrades.go
- app/upgrades/1_0_0_rc_4/upgrades.go
- app/upgrades/2_0_0/upgrades.go
- app/upgrades/3_0_0/upgrades.go
- app/upgrades/4_0_0/upgrades.go
- app/upgrades/4_0_1/upgrades.go
- app/upgrades/4_0_1/upgrades_test.go
- app/upgrades/latest/upgrades.go
- app/upgrades/upgrades.go
- interchaintest/chain_upgrade_test.go
- interchaintest/chain_v401_upgrade_test.go
- interchaintest/go.mod
- interchaintest/setup.go
Closes: https://github.com/archway-network/archway/issues/438
- modifying upgrade handlers to take in Account Keeper
- added v4.0.1 upgrade handler
- added interchain test - `TestFeeCollectorBurnChainUpgrade` - This test starts a chain with v2.0.0, upgrades it to v4.0.0 and then upgrades it to v4.0.1 and then checks if the fee collector account has burn permissions
> fix: upgrade handler missing burn permissions for feecollector account

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/4_0_2/upgrades.go
- app/upgrades/4_0_2/upgrades_test.go
- interchaintest/chain_v402_upgrade_test.go
- interchaintest/setup.go
- all references to v4.0.1 in the code renamed to v4.0.2 (this is because v4.0.1-rc.1 tag and v4.0.1 tag existing together make goreleaser's life a bit complicated)
> chore: retagging with v4.0.2 to prevent dual tagging of same commit 

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/latest/upgrades.go
- interchaintest/setup.go
- Adding `latest` upgrade handler for future dev work
- Adding release links to the changelog
> chore: Post v4.0.2 release maintenance 

- .goreleaser.yaml
- CHANGELOG.md
fixes a goreleasers missing image manifest `:` which results failed image creation
> fix: typo fix in goreleaser name template

- .goreleaser.yaml
- CHANGELOG.md
Fixes the goreleaser image tag, missin `:`
> fix: goreleaser dev image tag

- x/genmsg/module.go
- x/rewards/module.go
- x/tracking/module.go
This PR removes the following deprecated routes from the appmodule of all the modules x/genmsgs, x/rewards, x/tracking
- Route
- QuerierRoute
- LegacyQuerierHandler
> chore: remove deprecated appmodule routes

- app/ante.go
- app/app.go
- app/app_test.go
- app/export.go
- app/genesis.go
- app/sim_test.go
- app/test_helpers.go
- app/upgrades/2_0_0/upgrades.go
- app/upgrades/4_0_2/upgrades_test.go
- cmd/archwayd/genaccounts.go
- cmd/archwayd/main.go
- cmd/archwayd/root.go
- Updating the storekeys reference
- Updating the ante handlers 
- `ante.NewRejectExtensionOptionsDecorator()` => `ante.NewExtensionOptionsDecorator(options.ExtensionOptionChecker)`
- `ante.NewMempoolFeeDecorator()` => `ante.NewDeductFeeDecorator(options.AccountKeeper, options.BankKeeper, options.FeegrantKeeper, options.TxFeeChecker)`
- `ibcante.NewAnteDecorator(options.IBCKeeper)` => `ibcante.NewRedundantRelayDecorator(options.IBCKeeper)`
- Updating the app export to allow export by module
- Updating the simulation package references
- Removing `add-genesis-account` and explicit references to gentx cmds as this is now provided by gentx commands superset 
- Adding `consensusParamsKeeper`
> chore: updating app wiring

- app/app.go
- app/export.go
- app/keepers/keepers.go
- app/test_access.go
- app/upgrades/latest/upgrades.go
- scripts/localnet.sh
- Adding crisis module
- Adding consensus module
- Adding group module
- Adding nft module 
- Fixing bad wiring of staking keeper
- Fixing genesis gentx cmd and updating localnet script 
(pls ignore linter and tests. will fix in new PR)
🎉We have blocks now 🎉
```
12:15PM INF Catchup by replaying consensus messages height=1 module=consensus
12:15PM INF Replay: Done module=consensus
12:15PM INF service start impl=Evidence module=evidence msg="Starting Evidence service"
12:15PM INF service start impl=StateSync module=statesync msg="Starting StateSync service"
12:15PM INF service start impl=PEX module=pex msg="Starting PEX service"
12:15PM INF service start book=data/localnet-1/config/addrbook.json impl=AddrBook module=p2p msg="Starting AddrBook service"
12:15PM INF Saving AddrBook to file …
```
> chore: apply v47 changes

- .github/workflows/deploy.yaml
- CHANGELOG.md
Titus network is not used anymore so the deployment can be removed.
> chore: remove unused titus deployment from the pipeline

- .github/workflows/test.yaml
- CHANGELOG.md
The gh workflow which runs tests is named as `build` even tho the main thing it does is run the tests. So renaming the gh job to say "Run tests"
> ci: rename the gh workflow job name to be accurate

- x/rewards/keeper/min_cons_fee.go
- x/rewards/keeper/tracking.go
Fixing our logic for
- Updating min-consensus-fee
- Tracking inflationary rewards
because it was rugged by sdk 47 changes to the infiniteGasMeter https://github.com/cosmos/cosmos-sdk/pull/9651
Before (sdk 45)  && After (sdk 47)
> fix: updating logic for how we deal with infiniteGasMeter

- CHANGELOG.md
- Dockerfile.deprecated
- app/app.go
- app/app_test.go
- app/sim_test.go
- app/test_helpers.go
- cmd/archwayd/root.go
- e2e/testing/chain.go
- go.mod
- go.sum
- Bumping the wasmd fork to `v0.43.0-archway` https://github.com/archway-network/archway-wasmd/pull/9
- Removing all the wasmd related deprecated proposals as they were removed from the codebase. Should use v1 gov props now for wasmd 
- Updated Dockerfile with relevant wasmvm version. [checksum src](https://github.com/CosmWasm/wasmvm/releases)
> feat: bumping archway wasmd to v0.43.0

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/5_0_0/upgrades.go
- interchaintest/setup.go
- x/rewards/ante/min_cons_fee_test.go
- x/rewards/keeper/grpc_query_test.go
- x/rewards/keeper/withdraw_test.go
- Fixing lint where errors were not being checked against in tests
- Renaming upgrade handlers from `latest` to `v5.0.0`
- Update interchaintest version reference for chain upgrade test
- Updating chnagelog
> chore: v5 release changes 

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/latest/upgrades.go
- interchaintest/chain_upgrade_test.go
- interchaintest/setup.go
- adding new upgrade handler
- updating versions in interchaintest
- updating changelog
- updating the software upgrade prop in chainupgradetest to be x/gov v1
- removing the custom denom config for interchaintest genesis as the framework takes care of it
> chore: Post v5.0.0 release maintenance

- CHANGELOG.md
- app/app.go
this brings back rest endpoints in the app
> fix(app): rest endpoints

- CHANGELOG.md
- interchaintest/setup.go
The v5 release messed up the changelog. This PR attempts to fix it.
Plus setting the latest version of archway to the last release version. v5.0.2
> chore: fix the changelog

- CHANGELOG.md
- releasing-archway.md
Update the release process to properly account for Titus utilizing release candidates, including some additional local sanity checks.
> docs: Update release process

- x/callback/abci.go
- x/callback/keeper/fees.go
- x/callback/keeper/keeper.go
- x/callback/keeper/msg_server.go
- x/callback/types/expected_keepers.go
Handling fees in the following way for the following events
1. CancelCallback
`transactionFee` - Refund completely
`futureReservationFee` - Send to FeeCollector
`blockReservationFee` - Send to FeeCollector
`surplusFees` - Refund completely
2. ExecuteCallback
`transactionFee` - Calculate the amount of gas consumed and the total tx fees for that amount of gas. If the tx fees is lesser than what was paid, refund the rest to the address who reserved the callback. Send the tx fees to fee_collector.
`futureReservationFee` - Send to FeeCollector
`blockReservationFee` - Send to FeeCollector
`surplusFees` - Send to FeeCollector
> feat(x/callback): Handle fees

- CHANGELOG.md
- Dockerfile.deprecated
- go.mod
- go.sum
Ref: [CWA-2023-004](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md)
> chore: bump wasmvm to v1.5.1

- .github/workflows/interchaintest.yaml
- CHANGELOG.md
- interchaintest/setup.go
The previous gh action used did not detect release candidate tags. Which would cause issues in PRs.
Replacing with a better one.
> ci: fixing interchaintest issue with rc tags

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/6_0_0/upgrades.go
- interchaintest/setup.go
Closes: #510 
- Cleanup the changelog to match with the v6 release
- Rename the upgrade handlers from v5=>v6
- Update the initial version name in interchaintest to v6
- Added changelog entry for 4.0.3
> chore: Post v6.0.0 release maintenance

- CHANGELOG.md
- app/app.go
- app/upgrades/7_0_0/upgrades.go
- x/callback/types/params.go
- x/cwerrors/types/params.go
- x/cwica/genesis.go
- x/cwica/keeper/grpc_query.go
- x/cwica/keeper/grpc_query_test.go
- x/cwica/keeper/ibc_handlers.go
- x/cwica/keeper/keeper.go
- x/cwica/keeper/msg_server.go
- x/cwica/keeper/msg_server_test.go
- x/cwica/keeper/params.go
- x/cwica/keeper/params_test.go
- x/cwica/module.go
- x/cwica/types/keys.go
- x/cwica/types/params.go
- Refactor x/cwica module params to be stored using the collections api
- Set default values for module params in the upgrade handler
> feat: update new module params for upgrade + refactor x/cwica params to use collections

- CHANGELOG.md
- app/upgrades/7_0_0/upgrades.go
- x/callback/keeper/fees.go
- x/callback/types/msg.go
- removing the use of sdk.DefaultBondDenom as its not set accurately on titus and results in bad config
> fix: fixing wrong bond denom being considered for callback fees

- CHANGELOG.md
- x/cwerrors/keeper/msg_server_test.go
- x/cwerrors/keeper/subscriptions.go
when cwerrors subscription was being set, the fees was deducted from the contract account instead of the sender address
> fix(x/cwerrors): send fees from the sender account instead of contract account

- CHANGELOG.md
- x/cwerrors/keeper/keeper.go
- x/cwerrors/keeper/msg_server_test.go
- x/cwerrors/keeper/subscriptions.go
- x/cwerrors/keeper/subscriptions_test.go
- x/cwerrors/keeper/sudo_errors.go
- x/cwerrors/types/errors.go
- Ensuring user doesnt overpay for contract subscriptions
- When user resubscribes to error callback(before the existing subscription ends), extend the subscription end date instead of resetting the end date
- Removing some redundant values stored in the module collections (when value is part of the key)
> fix(x/cwerrors): audit remediations

- CHANGELOG.md
- app/app_upgrades.go
- app/upgrades/latest/upgrades.go
- interchaintest/setup.go
Closes: https://github.com/archway-network/archway/issues/555
> chore: Post v7.0.0 release maintenance

- CHANGELOG.md
- x/callback/keeper/callback.go
Params were being fetched two times in same func. Removed the second time
> refactor(x/callback): Remove redundant code in SaveCallback

- CHANGELOG.md
- app/app.go
- x/cwerrors/spec/03_end_block.md
- x/cwerrors/spec/README.md
- x/cwica/ibc_module.go
- x/cwica/keeper/ibc_handlers.go
- x/cwica/keeper/ibc_handlers_test.go
- x/cwica/spec/02_messages.md
- x/cwica/spec/06_ibc.md
- x/cwica/spec/README.md
- x/cwica/types/errors.go
Addressed the following:
- Move cwerrors endblocker to the end of all the endblocker invocations
- Documentation updates for x/cwerrors
- Documentation updates for x/cwica
- Some code cleanup of removing unused enums and values
> fix: audit remediations 

- .github/workflows/proto-registry.yaml
- CHANGELOG.md
Automatically publish the protocol's ProtoBuf files to the [Buf Schema Registry](https://buf.build/archway-network/archway)
> ci(proto): automatically publish proto files

- .github/workflows/proto-registry.yaml
- CHANGELOG.md
The `buf` CLI v1.32 seems to have an undocumented breaking change and won't accept the `buf.yaml` file structure defined on `v1`.
This is possibly a bug on their side since it's [mentioned in the changelog](https://github.com/bufbuild/buf/releases/tag/v1.32.0) that the CLI is backwards compatible with `v1` projects.
> ci(proto): use buf 1.31 to push files

- CHANGELOG.md
- go.mod
- go.sum
Bumping versions to apply fixes introduced on https://github.com/archway-network/archway-wasmd/pull/14
> build: bump wasmvm to 1.5.4 and wasmd fork to 0.50.1
